variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: devops-acr-connection
  imageRepository: devops-course-repository
  containerRegistry: devopscourseregistry118
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: 'latest'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

steps:

- task: AzureWebAppContainer@1 # Description what the task will execute
  inputs:
    azureSubscription: 'devops-appservice-resource-group'
    appName: 'Devops-course-webapp-tests'
    containers: $(containerRegistry)/$(imageRepository):$(tag)
